### ISSUE TITLE
SOLLER Category Covariate

### ISSUE THREAD

**Issue by ghost** [scworland/restore-2018#32]
Of our six categorical covariates, only soller has a different "nodata" from the rest. What follows is my change over in the final filtering of the covariates file. I am leaving this as an Issue in case it has any cascading impact of SCW code base---It does not on mine.

`df$perennial_ice_snow <- NULL`
`df$soller[df$soller == "cat_soller_nodata"] <- "nodata"`

This operation now ensures that no data is `nodata` throughout.

**Comment by scworland-usgs** [comment]
Is this for the huc12 or gage data? I am going to respond

**Comment by wasquith-usgs** [comment]
Just confirming your email, there is one cat_soller_nodata in the gage
data. I need to filter that too. Darn. My filter is updated and committed
to git.

William H. Asquith, Research Hydrologist
U.S. Geological Survey, Science Building MS-1053
Texas Tech University, Lubbock, Texas 79409
806-742-3129 work; 806-392-4148 cell
